FROM amazoncorretto:11-alpine

WORKDIR /app

ENV PROFILES=prod

ARG ORIGINAL_JAR_FILE=./build/libs/product-service-1.0.0.jar

COPY ${ORIGINAL_JAR_FILE} product-service.jar

CMD ["java", "-Dspring.profiles.active=${PROFILES}", "-jar", "/app/product-service.jar"]
