server:
  port: 8085
spring:
  config:
    activate:
      on-profile: local,dev,prod
  application:
    name: product-service
  # config service settings
  cloud:
    config:
      name: product-service
  jackson:
    time-zone: Asia/Seoul
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh